### ISSUE TITLE
Spinner colors aren't changing

### ISSUE THREAD

**Issue by xrayian** [leonzalion/vue3-spinners#1]
### Here's my implementation
I used options api for the import

```vue
<template>
    <div v-if="loading">
        <vue-spinner size="60" color="red" />
    </div>
</template>
```

```ts
import { VueSpinner } from 'vue3-spinners';
export default defineComponent({
    components: {
        VueSpinner
    },
});
```

The spinner insists on using the `currentColor` if I use the color prop

**Comment by xrayian** [comment]
Found a temporary solution
`<vue-spinner size="60" style="color: red" />`

**Comment by leonsilicon** [comment]
Thanks for reporting the bug; it should be fixed in the latest version!
